DEEPSEEK_API_KEY = "sk-b4239a180f2f4cfeb1ac9795ce222318"

OPENAI_API_KEY = "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"

GOOGLE_API_KEY = "AIzaSyDBEnEJM1m4SOo-5O7y5f5pwU_bE9g4xKo"
